version: '3'
services:
  tic-tac-toe:
    image: tic-tac-toe:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - tic-tac-net

networks:
  tic-tac-net:
    driver: bridge
